### ISSUE TITLE
درخواست ترجمه برای بخش [نام بخش مورد نظر خود را در اینجا بنویسید]

### ISSUE THREAD

**Issue by kardohmi** [flaskcwg/flask-docs-fa#10]
<div dir="rtl">

چک لیست:

- [ ] اسناد را به صورت محلی بسازید، (باید بدون هشدار یا خطا باشد).
- [ ] اگر اولین مترجم هستید، کامنت «FIRST AUTHOR <EMAIL@ADDRESS>» را در فایل «.po» به‌روزرسانی کنید.
- [ ] مقدار فیلد «Last-Translator» را در فایل «.po» به‌روزرسانی کنید.
- [ ]  «pre-commit» را اجرا کنید و مشکلات را برطرف کنید.

</div>

**Comment by mmdbalkhi** [comment]
سلام @kardohmi  ممنون بابت اینکه ایشو باز کردید ولی لطفا اطلاعات دقیقی درباره اینکه کدام بخش دو میخواین ترجمه کنید بگین.
