### ISSUE TITLE
درخواست ترجمه برای بخش testing.po

### ISSUE THREAD

**Issue by mmdbalkhi** [flaskcwg/flask-docs-fa#14]
<div dir="rtl">

چک لیست:

- [X] اسناد را به صورت محلی بسازید، (باید بدون هشدار یا خطا باشد).
- [X] اگر اولین مترجم هستید، کامنت «FIRST AUTHOR <EMAIL@ADDRESS>» را در فایل «.po» به‌روزرسانی کنید.
- [X] مقدار فیلد «Last-Translator» را در فایل «.po» به‌روزرسانی کنید.

</div>

**Comment by MDK84** [comment]
سلام
ترجمه خیلی خوب و روان هست
با تشکر از شما

**Comment by mmdbalkhi** [comment]
@MDK84 

ممنون ولی لطفا از دفعات بعد تست هم بکنید اجرا رو یعنی اول کلون پول ریکوئست کنید بعد:
```sh
virtualenv venv
source venv/bin/activate
pip install -r requirements/docs.txt
pip install -e .
cd docs
make dirhtml
```

و برای بررسی خروجی:
```
python -m http.http --dir _build/dirhtml
```
