### ISSUE TITLE
درخواست ترجمه برای بخش deploying

### ISSUE THREAD

**Issue by MDK84** [flaskcwg/flask-docs-fa#15]
<div dir="rtl">

# چک لیست:

* [X] این بخش قبلا ترجمه نشده است

> اگر میخواهید مشکلی در ترجمه را حل کنید نیازی به ساخت ایشو نیست و فقط PR خود را ایجاد کنید.

* [X] poedit یا نرم افزاری مشابه را نصب کرده‌اید و طریقه کار با آن را میدانید.

> البته اجباری برای استفاده از یک برنامه برای ترجمه فایل های `.po` نیست ولی پیشنهاد میکنیم که از یک برنامه کمکی برای ترجمه استفاده کنید.
</div>

## TODO:

- [x] asgi
- [x] cgi
- [x] fastcgi
- [ ] index
- [ ] mod_wsgi
- [ ] uwsgi
- [ ] wsgi-standalone

**Comment by mmdbalkhi** [comment]
@MDK84 سلام.
اگر بخشی از ترجمه رو انجام دادید لطفا پوش کنید در غیر اینصورت منتظر ترجمه شما هستیم.
