### ISSUE TITLE
Missing Hypercorn link in deploying/asgi

### ISSUE THREAD

**Issue by Jalkhov** [flaskcwg/flask-docs-fa#41]
Hello, in the `.po` file of the section mentioned in the title, the link to `Hypercorn` is missing, I attach screenshots of the documentation for better understanding:

English version
![imagen](https://user-images.githubusercontent.com/36505934/175792264-9928f0b8-8691-44ae-a9d1-050803298274.png)

Persian version
![imagen](https://user-images.githubusercontent.com/36505934/175792254-f225cad2-17f9-42b5-b973-898769de43a9.png)

As an attachment, if you look [here](https://github.com/flaskcwg/flask-docs-fa/blob/f3ce22072ec5f135ffd43e29edd4e064f22cf68e/docs/locales/fa/LC_MESSAGES/deploying/asgi.po#L45-L46) the respective problematic line is marked in red, if I am not mistaken it is just a formatting problem.

**Comment by mmdbalkhi** [comment]
@Jalkhov thank you.
