### ISSUE TITLE
server.po ترجمه 

### ISSUE THREAD

**Issue by Abol-010** [flaskcwg/flask-docs-fa#51]
# چک لیست:

* [X] این بخش قبلا ترجمه نشده است

> اگر میخواهید مشکلی در ترجمه را حل کنید نیازی به ساخت ایشو نیست و فقط PR خود را ایجاد کنید.

<div dir="rtl">

* [ ] poedit یا نرم افزاری مشابه را نصب کرده‌اید و طریقه کار با آن را میدانید.

</div>

> البته اجباری برای استفاده از یک برنامه برای ترجمه فایل های `.po` نیست ولی پیشنهاد میکنیم که از یک برنامه کمکی برای ترجمه استفاده کنید.

**Comment by mmdbalkhi** [comment]
@Abol-010 ممنون از مشارکتتون.

**Comment by Abol-010** [comment]
درود
 عذرمیخوام فورک و PR رو پاک کردم.
 من دومین PR رو هم فرستادم ولی دیدم انگار بازم مشکل داره چندین بار سعی کردم درستش کنم ولی مثل اینکه مشکل داشت بازم
 آخرش نا امید شدم کامل پاک کردم 
 تونستید مشکل رو پیدا کنید؟ 
 من حدس میزنم سمت من یه تعدادی از requirement ها و dependency مشکل داشتن و نصب نمیشدن گاها مجبور میشدم دستی نصب کنم

**Comment by Abol-010** [comment]
حقیقتش این اولین تجربه من از کانتریبیوت تو یه پروژه ای تو گیت هاب بود همه چیو درست انجام دادم از ترجمه تا push کردن تغییرات ولی این PR که درست build نمیشد خیلی ناا میدم کرد

**Comment by mmdbalkhi** [comment]
مشکل این بود:

```diff
-` flask`
+`flask`
```
کاراکتر ` با flask فاصله داشت و نچسبیده بود.

**Comment by Abol-010** [comment]
همین یه چیز کوچیک فقط..
بازم ممنون 
من فورک میکنم پروژه رو اگه وقت آزاد داشتم بقیه فایلای poرو دونه دونه ترنسلیت میکنم.
